- hosts: master
  become: yes
  become_user: ubuntu
  tasks:
  - name: Get Master Node Ready
    shell: while kubectl get nodes | grep -i "NotReady"; do sleep 5; done
    
  - name: Get Master Node Status
    shell: kubectl get nodes >> nodestatus.txt
    args:
      chdir: $HOME
      creates: nodestatus.txt
   
  
