apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deploy
spec:
   replicas: 5
   selector:
      matchLabels:
         app: nginx-sample
   template:
      metadata:
         labels:
            app: nginx-sample
      spec:
         containers:
           - name: nginx-container
             image: nginx:latest
             ports:
             - containerPort: 80
               hostPort: 30011
