apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
   labels:
        zone: prod
        version: 1.1.1
spec:
  containers:
          - name: nginx-container
            image: nginx:latest
            ports:
            - containerPort: 80        
