apiVersion: v1
kind: ReplicationController
metadata:
   name: nginx-rc
spec:
   replicas: 10
   selector:
      app: nginx-sample
   template:
      metadata:
         labels:
            app: nginx-sample
      spec:        
         containers:
           - name: nginx-container
             image: nginx:latest
             ports:
             - containerPort: 80        
