apiVersion: v1
kind: Service
metadata:
   name: nginx-svc
   labels:
      app: nginx-sample
spec:
   type: NodePort
   ports:
     - port: 80
       nodePort: 30033
       protocol: TCP
   selector:
     app: nginx-sample
