apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: example-service
spec:
  ports:
  - port: 80
    targetPort: 4000
  type: NodePort
  selector:
    app: example-pod

apiVersion: v1
kind: Service
metadata:
   name: nginx-svc
   labels:
      app:nginx-sample
spec:
   type: NodePort
   ports:
     - port: 80
       nodePort: 30222
       protocol: TCP
   selector:
     app: nginx-sample

